### ISSUE TITLE
Could not get assembly path 

### ISSUE THREAD

**Issue by hhdd92** [microsoft/eventtracing-processing#6]
Hi,

I am using this library in my tool and I also build my tool as a standalone exe. It is based on .net 5.0. However, when I run my code as standalone exe, I got the below error, but if I build it regularly, it works well. Could you help to take a look this issue and provide some suggestions? Thank you.

Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'path1')
   at System.IO.Path.Combine(String path1, String path2)
   at Microsoft.Windows.EventTracing.ToolkitTraceProcessingEngine.GetProcessBinDirectoryDefaultToolkitPath(Assembly possibleEntryAssembly, String binDirectory)
   at Microsoft.Windows.EventTracing.ToolkitTraceProcessingEngine.GetOrCreateDefaultToolkitPath(TextWriter output)
   at Microsoft.Windows.EventTracing.ToolkitTraceProcessingEngine.Create(String path, ITraceProcessorSettings settings, ITraceProcessorSettings& effectiveSettings)
   at Microsoft.Windows.EventTracing.TraceProcessor.Create(String path, ITraceProcessorSettings settings)
   at Microsoft.Windows.EventTracing.TraceProcessor.Create(String path)

**Comment by hhdd92** [comment]
We have figured out to use fody to create standalone exe. That one works well so far. Close this issue.
